import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from "@react-pdf/renderer";

import type { WireReceipt } from "./types";

interface Props {
  receipt: WireReceipt;
}
const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 11,
    fontFamily: "Helvetica",
    color: "#1e293b",
  },

  header: {
    borderBottom: 1,
    borderBottomColor: "#d1d5db",
    paddingBottom: 20,
    marginBottom: 25,
  },

  bank: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#059669",
  },

  title: {
    marginTop: 6,
    fontSize: 18,
    fontWeight: "bold",
  },

  section: {
    marginBottom: 22,
  },

  sectionTitle: {
    fontSize: 13,
    fontWeight: "bold",
    marginBottom: 10,
    color: "#111827",
  },

  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 6,
    borderBottom: 1,
    borderBottomColor: "#f1f5f9",
    paddingBottom: 4,
  },

  label: {
    color: "#64748b",
  },

  value: {
    fontWeight: "bold",
  },

  amountBox: {
    marginVertical: 20,
    backgroundColor: "#ecfdf5",
    padding: 18,
    borderRadius: 8,
    border: "1 solid #10b981",
  },

  amount: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#047857",
    textAlign: "center",
  },

  footer: {
    marginTop: 40,
    borderTop: 1,
    borderTopColor: "#d1d5db",
    paddingTop: 20,
    fontSize: 9,
    color: "#64748b",
    textAlign: "center",
  },
});

export default function WireReceiptPdf({
  receipt,
}: Props) {
  return (
    <Document>

      <Page
        size="A4"
        style={styles.page}
      >

        <View style={styles.header}>

          <Text style={styles.bank}>
            APEX NATIONAL BANK
          </Text>

          <Text style={styles.title}>
            Official Wire Transfer Receipt
          </Text>

        </View>

        <View style={styles.amountBox}>

          <Text style={styles.amount}>
            ${receipt.summary.total.toLocaleString()}
          </Text>

        </View>

        <View style={styles.section}>

          <Text style={styles.sectionTitle}>
            Transaction Summary
          </Text>

          <Row
            label="Reference"
            value={receipt.summary.reference}
          />

          <Row
            label="Confirmation"
            value={
              receipt.summary.confirmationNumber ??
              "-"
            }
          />

          <Row
            label="Amount"
            value={`$${receipt.summary.amount.toLocaleString()}`}
          />

          <Row
            label="Fee"
            value={`$${receipt.summary.fee.toLocaleString()}`}
          />

          <Row
            label="Total"
            value={`$${receipt.summary.total.toLocaleString()}`}
          />

        </View>

        <View style={styles.section}>

          <Text style={styles.sectionTitle}>
            Sender
          </Text>

          <Row
            label="Name"
            value={receipt.sender.name}
          />

          <Row
            label="Bank"
            value={receipt.sender.bank}
          />

          <Row
            label="Account"
            value={receipt.sender.accountNumber}
          />

        </View>

        <View style={styles.section}>

          <Text style={styles.sectionTitle}>
            Recipient
          </Text>

          <Row
            label="Name"
            value={receipt.recipient.name}
          />

          <Row
            label="Bank"
            value={receipt.recipient.bank}
          />
<Row
  label="Wire Trace Number"
  value={
    receipt.summary.traceNumber ??
    "-"
  }
/>
          <Row
            label="Account"
            value={receipt.recipient.accountNumber}
          />

        </View>

        <View style={styles.footer}>

          <Text>
            This receipt was electronically generated by Apex National Bank.
          </Text>

          <Text>
            Official Customer Copy
          </Text>

        </View>

      </Page>

    </Document>
  );
}

function Row({
  label,
  value,
}: {
  label: string;
  value: string;
}) {
  return (
    <View style={styles.row}>
      <Text style={styles.label}>
        {label}
      </Text>

      <Text style={styles.value}>
        {value}
      </Text>
    </View>
  );
}