"use client";

import {
  ShieldCheck,
  QrCode,
  Fingerprint,
  BadgeCheck,
  Hash,
} from "lucide-react";

interface Props {
  reference: string;
  confirmation?: string;
}

export function ReceiptQRCode({
  reference,
  confirmation,
}: Props) {
  return (
    <section className="overflow-hidden rounded-2xl border bg-white shadow-sm">

      {/* Header */}

      <div className="border-b bg-gradient-to-r from-slate-50 to-white px-6 py-5">

        <div className="flex items-center gap-3">

          <ShieldCheck className="h-6 w-6 text-emerald-600" />

          <div>

            <h2 className="text-xl font-bold text-slate-900">
              Receipt Verification
            </h2>

            <p className="text-sm text-slate-500">
              Verify the authenticity of this transaction using the QR code or
              reference information below.
            </p>

          </div>

        </div>

      </div>

      {/* Content */}

      <div className="grid gap-8 p-6 lg:grid-cols-[1fr_280px]">

        {/* Left */}

        <div className="space-y-5">

          <InfoRow
            icon={<Hash className="h-5 w-5 text-emerald-600" />}
            label="Transfer Reference"
            value={reference}
          />

          <InfoRow
            icon={<BadgeCheck className="h-5 w-5 text-emerald-600" />}
            label="Confirmation Number"
            value={confirmation ?? "Pending Assignment"}
          />

          <InfoRow
            icon={<Fingerprint className="h-5 w-5 text-emerald-600" />}
            label="Digital Verification"
            value="Authenticated by Apex National Bank"
          />

          <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-5">

            <div className="flex items-start gap-3">

              <ShieldCheck className="mt-0.5 h-6 w-6 text-emerald-600" />

              <div>

                <h3 className="font-semibold text-emerald-800">
                  Secure Electronic Record
                </h3>

                <p className="mt-2 text-sm leading-6 text-emerald-700">
                  This receipt was digitally generated by Apex National Bank.
                  Every transaction is assigned a unique reference and
                  confirmation record to support customer verification,
                  compliance review, and audit requirements.
                </p>

              </div>

            </div>

          </div>

        </div>

        {/* QR */}

        <div className="flex flex-col items-center justify-center rounded-2xl border bg-slate-50 p-6">

          <div className="flex h-56 w-56 items-center justify-center rounded-2xl border-2 border-dashed border-slate-300 bg-white shadow-sm">

            {/* Replace with actual QR component later */}

            <QrCode className="h-32 w-32 text-slate-500" />

          </div>

          <p className="mt-5 text-center text-sm text-slate-500">
            Scan to verify this receipt using the Apex National Bank
            verification service.
          </p>

        </div>

      </div>

      {/* Footer */}

      <div className="border-t bg-slate-50 px-6 py-4">

        <p className="text-center text-xs leading-6 text-slate-500">
          The QR verification service confirms receipt authenticity only. It
          does not disclose confidential account or customer information.
        </p>

      </div>

    </section>
  );
}

interface InfoRowProps {
  label: string;
  value: string;
  icon: React.ReactNode;
}

function InfoRow({
  label,
  value,
  icon,
}: InfoRowProps) {
  return (
    <div className="rounded-xl border border-slate-200 bg-slate-50 p-5">

      <div className="mb-3 flex items-center gap-2">

        {icon}

        <span className="text-sm font-medium text-slate-600">
          {label}
        </span>

      </div>

      <div className="break-all font-mono text-base font-bold text-slate-900">
        {value}
      </div>

    </div>
  );
}