"use client";

import {
  ShieldCheck,
  Building2,
  Phone,
  Globe,
  Mail,
  Lock,
} from "lucide-react";

export function ReceiptFooter() {
  return (
    <footer className="mt-10 overflow-hidden rounded-2xl border bg-white shadow-sm">

      {/* Security Banner */}

      <div className="border-b bg-gradient-to-r from-emerald-600 to-emerald-700 px-6 py-5 text-white">

        <div className="flex flex-col gap-4 md:flex-row md:items-center">

          <ShieldCheck className="h-10 w-10 shrink-0" />

          <div>

            <h3 className="text-lg font-bold">
              Official Apex National Bank Receipt
            </h3>

            <p className="mt-1 text-sm text-emerald-100">
              This electronic receipt was securely generated by Apex National
              Bank and serves as confirmation of the transaction shown above.
            </p>

          </div>

        </div>

      </div>

      {/* Information */}

      <div className="grid gap-8 p-6 md:grid-cols-3">

        {/* Bank */}

        <div>

          <div className="mb-3 flex items-center gap-2">

            <Building2 className="h-5 w-5 text-emerald-600" />

            <h4 className="font-semibold">
              Apex National Bank
            </h4>

          </div>

          <p className="text-sm leading-6 text-slate-600">
            Secure digital banking solutions designed to protect every
            transaction with enterprise-grade security and regulatory
            compliance.
          </p>

        </div>

        {/* Contact */}

        <div>

          <div className="mb-3 flex items-center gap-2">

            <Phone className="h-5 w-5 text-emerald-600" />

            <h4 className="font-semibold">
              Customer Support
            </h4>

          </div>

          <div className="space-y-2 text-sm text-slate-600">

            <div className="flex items-center gap-2">

              <Mail className="h-4 w-4" />

              support@apexnationalbank.com

            </div>

            <div className="flex items-center gap-2">

              <Phone className="h-4 w-4" />

              +1 (800) 555-0100

            </div>

            <div className="flex items-center gap-2">

              <Globe className="h-4 w-4" />

              www.apexnationalbank.com

            </div>

          </div>

        </div>

        {/* Security */}

        <div>

          <div className="mb-3 flex items-center gap-2">

            <Lock className="h-5 w-5 text-emerald-600" />

            <h4 className="font-semibold">
              Security Notice
            </h4>

          </div>

          <p className="text-sm leading-6 text-slate-600">
            Keep this receipt for your records. If you did not authorize this
            transaction, contact Apex National Bank immediately.
          </p>

        </div>

      </div>

      {/* Legal */}

      <div className="border-t bg-slate-50 px-6 py-5">

        <div className="space-y-3 text-center">

          <p className="text-xs leading-6 text-slate-500">

            This receipt was electronically generated and requires no
            handwritten signature. Transaction records are maintained in
            accordance with applicable banking regulations and internal
            retention policies.

          </p>

          <div className="flex flex-wrap items-center justify-center gap-4 text-xs font-medium text-slate-500">

            <span>Member FDIC</span>

            <span>•</span>

            <span>Equal Housing Lender</span>

            <span>•</span>

            <span>SSL Secured</span>

            <span>•</span>

            <span>PCI DSS Compliant</span>

          </div>

          <p className="text-xs text-slate-400">

            © {new Date().getFullYear()} Apex National Bank. All Rights
            Reserved.

          </p>

        </div>

      </div>

    </footer>
  );
}