"use client";

import jsPDF from "jspdf";

interface Props {
  amount: number;
  recipient: string;
  email: string;
  account: string;
  reference: string;
  memo: string;
  status: string;
  date: string;
}

export default function DownloadReceiptButton({
  amount,
  recipient,
  email,
  account,
  reference,
  memo,
  status,
  date,
}: Props) {
  function download() {
    const pdf = new jsPDF();

    pdf.setFontSize(22);
    pdf.text("Apex National Bank", 20, 20);

    pdf.setFontSize(16);
    pdf.text("Zelle Transfer Receipt", 20, 35);

    pdf.line(20, 40, 190, 40);

    let y = 55;

    const rows = [
  ["Amount", `$${amount.toFixed(2)}`],
  ["Recipient", recipient ?? ""],
  ["Recipient Email", email ?? ""],
  ["From Account", account ?? ""],
  ["Reference", reference ?? ""],
  ["Status", status ?? ""],
  ["Memo", memo || "None"],
  ["Date", date ?? ""],
];

    rows.forEach(([label, value]) => {
     pdf.setFont("helvetica", "bold");
      pdf.text(`${label}:`, 20, y);

      pdf.setFont("helvetica", "normal");
      pdf.text(String(value), 75, y);

      y += 12;
    });

    pdf.line(20, y + 5, 190, y + 5);

    pdf.setFontSize(10);
    pdf.text(
      "This document is an official payment receipt generated by Apex National Bank.",
      20,
      y + 20
    );

    pdf.save(`Receipt-${reference ?? "receipt"}.pdf`);
  }

  return (
    <button
      onClick={download}
      className="flex-1 rounded-lg bg-black py-3 font-medium text-white transition hover:bg-black/90"
    >
      Download Receipt
    </button>
  );
}